# Generated by Django 6.0.3 on 2026-04-14 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_appointment_user'),
        ('learnapp', '0002_userdetails_address_userdetails_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('yop', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(choices=[('BLOOD TEST', 'Blood Test'), ('URINE TEST', 'Urine Test'), ('X-RAY', 'X-Ray'), ('MRI', 'MRI'), ('CT SCAN', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG'), ('EEG', 'EEG'), ('BIOPSY', 'Biopsy'), ('ALLERGY TEST', 'Allergy Test')], max_length=100)),
                ('lab_results', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_range', models.CharField(choices=[('nil', 'Nil'), ('positive', 'Positive'), ('negative', 'Negative'), ('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=100)),
                ('result_description', models.TextField(max_length=500)),
                ('test_cost', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
                ('reffered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
