# Generated by Django 6.0.3 on 2026-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreports', '0003_alter_lab_test_result_range_alter_lab_test_test_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='test_duration',
            field=models.CharField(default='4 hrs', max_length=50),
        ),
    ]
