# Generated by Django 6.0.3 on 2026-04-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('room_type', models.CharField(choices=[('COMMON', 'Common Ward'), ('SEMI', 'Semi Private'), ('PRIVATE_AC', 'Private AC'), ('PRIVATE_NON_AC', 'Private Non AC'), ('DELUX', 'Delux')], max_length=20)),
                ('food_required', models.BooleanField(default=False)),
                ('total_days', models.IntegerField()),
                ('room_charges', models.IntegerField(default=0)),
                ('doctor_charges', models.IntegerField(default=0)),
                ('nursing_charges', models.IntegerField(default=0)),
                ('medicine_charges', models.IntegerField(default=0)),
                ('food_charges', models.IntegerField(default=0)),
                ('total_bill', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
