# Generated by Django 6.0.3 on 2026-04-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alldoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialized', models.CharField(choices=[('GENERAL MEDICIENE', 'General Medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ORTHOPEDIC', 'orthopedic'), ('EYE SPECIALIST', 'eye specialist'), ('ENT', 'ent'), ('DENTIST', 'dentist'), ('NUEROLOGIST', 'nuerologist'), ('GYNOCOLOGIST', 'Gynocologist'), ('CHILD SPECIALIST', 'Child Specialist'), ('OTHERS', 'other')])),
                ('YOE', models.PositiveIntegerField()),
                ('lic_no', models.CharField(max_length=50)),
                ('certification', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('consultation_charge', models.CharField(default=550, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Alltreatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentname', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('GENERAL MEDICIENE', 'General Medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ORTHOPEDIC', 'orthopedic'), ('EYE SPECIALIST', 'eye specialist'), ('ENT', 'ent'), ('DENTIST', 'dentist'), ('NUEROLOGIST', 'nuerologist'), ('GYNOCOLOGIST', 'Gynocologist'), ('CHILD SPECIALIST', 'Child Specialist'), ('OTHERS', 'other')])),
                ('description', models.CharField(max_length=500)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
