# Generated by Django 6.0.3 on 2026-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldoctors',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
